# Ingress for services requiring path stripping (Rewrites)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: medinsight-infra-ingress
  namespace: medinsight
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: medinsightpds.duckdns.org
    http:
      paths:
      - path: /pgadmin(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: pgadmin
            port:
              number: 80
      - path: /eureka(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: discovery-service
            port:
              number: 8761
      # Easy access to Keycloak UI (strips /keycloak)
      - path: /keycloak(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: keycloak
            port:
              number: 8080
      # Compatibility for legacy /auth prefix (strips /auth)
      - path: /auth(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: keycloak
            port:
              number: 8080
