global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'microservices'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: 
        - 'medinsight-gateway:8080'
        - 'medinsight-auth-service:8081'
        - 'medinsight-appointment-service:8082'
        - 'medinsight-medical-record-service:8084'
        - 'medinsight-audit-service:8085'
        - 'medinsight-mail-service:8087'
        - 'medinsight-discovery:8761'
